# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/spades',
                'doc_host': 'https://kanglcn.github.io',
                'git_url': 'https://github.com/kanglcn/spades',
                'lib_path': 'spades'},
  'syms': {'spades.core': {'spades.core.foo': ('core.html#foo', 'spades/core.py')}}}
